//! Commands invoked from the React shell outside the API layer
//! (`main.tsx`, `App.tsx`, `theme-provider.tsx`, `clipboard.ts`,
//! `DatabaseUpgrade.tsx`). Hand-written; not regenerated by gen_api.mjs.
#![allow(dead_code)]

use cc_switch_contract::commands::app as cmd;
use cc_switch_contract::IpcError;
use serde_json::json;

use crate::ipc;

/// Mirrors the native window theme; `theme` is `light`, `dark` or `system`.
pub async fn set_window_theme(theme: &str) -> Result<(), IpcError> {
    ipc::invoke(cmd::SET_WINDOW_THEME, &json!({ "theme": theme })).await
}

/// Startup error captured by the backend (e.g. database too new), if any.
pub async fn get_init_error() -> Result<serde_json::Value, IpcError> {
    ipc::invoke_no_args(cmd::GET_INIT_ERROR).await
}

pub async fn copy_text_to_clipboard(text: &str) -> Result<(), IpcError> {
    ipc::invoke(cmd::COPY_TEXT_TO_CLIPBOARD, &json!({ "text": text })).await
}

pub async fn get_migration_result() -> Result<serde_json::Value, IpcError> {
    ipc::invoke_no_args(cmd::GET_MIGRATION_RESULT).await
}

pub async fn get_skills_migration_result() -> Result<serde_json::Value, IpcError> {
    ipc::invoke_no_args(cmd::GET_SKILLS_MIGRATION_RESULT).await
}

pub async fn check_app_update_available() -> Result<serde_json::Value, IpcError> {
    ipc::invoke_no_args(cmd::CHECK_APP_UPDATE_AVAILABLE).await
}

pub async fn install_update_and_restart() -> Result<(), IpcError> {
    ipc::invoke_no_args(cmd::INSTALL_UPDATE_AND_RESTART).await
}

pub async fn open_external(url: &str) -> Result<(), IpcError> {
    ipc::invoke(cmd::OPEN_EXTERNAL, &json!({ "url": url })).await
}

pub async fn open_app_config_folder() -> Result<(), IpcError> {
    ipc::invoke_no_args(cmd::OPEN_APP_CONFIG_FOLDER).await
}
