//! Typed wrappers over the Tauri commands, one module per backend area.
//! Generated by tools/gen_api.mjs from src/lib/api/*.ts; hand-edited as
//! views are ported.

pub mod app;
pub mod auth;
pub mod config;
pub mod connectivity_check;
pub mod copilot;
pub mod deeplink;
pub mod env;
pub mod failover;
pub mod global_proxy;
pub mod hermes;
pub mod mcp;
pub mod model_fetch;
pub mod omo;
pub mod openclaw;
pub mod profiles;
pub mod prompts;
pub mod providers;
pub mod proxy;
pub mod sessions;
pub mod settings;
pub mod skills;
pub mod subscription;
pub mod usage;
pub mod vscode;
pub mod workspace;
