//! `assets/tailwind.css` is produced by the `dx` Tailwind watcher and is not
//! committed. Plain `cargo check`/`cargo build` still need the file to exist
//! because `asset!()` resolves paths at compile time, so create an empty
//! placeholder when it is missing.

use std::fs;
use std::path::Path;

fn main() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("assets")
        .join("tailwind.css");
    if !path.exists() {
        let _ = fs::create_dir_all(path.parent().unwrap());
        let _ = fs::write(
            &path,
            "/* placeholder: generated by `dx` from tailwind.css */\n",
        );
    }
    println!("cargo:rerun-if-changed=tailwind.css");
    println!("cargo:rerun-if-changed=build.rs");
}
