#!/usr/bin/env python3
"""Regenerates crates/cc-switch-contract/src/commands.rs from the React API
layer (src/lib/api/*.ts plus the few stray invoke() call sites).

Migration-time scaffolding: the TS files remain the reference until the React
UI is removed. Run: python3 scripts/gen-contract-commands.py
"""
import collections
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INVOKE = re.compile(r'invoke(?:<[^>]*>)?\(\s*["\']([A-Za-z0-9_]+)["\']', re.S)
STRAYS = {
    "proxy": ["src/hooks/useProxyStatus.ts", "src/hooks/useProxyConfig.ts"],
    "app": [
        "src/components/DatabaseUpgrade.tsx",
        "src/App.tsx",
        "src/components/theme-provider.tsx",
        "src/lib/clipboard.ts",
        "src/main.tsx",
    ],
}


def snake(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).replace("-", "_").lower()


def main() -> None:
    groups: "collections.OrderedDict[str, set[str]]" = collections.OrderedDict()

    def add(module: str, rel: str) -> None:
        with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
            found = set(INVOKE.findall(fh.read()))
        if found:
            groups.setdefault(module, set()).update(found)

    for path in sorted(glob.glob(os.path.join(ROOT, "src/lib/api/*.ts"))):
        base = os.path.basename(path)[:-3]
        if base in ("index", "types"):
            continue
        add(snake(base), os.path.relpath(path, ROOT))
    for module, files in STRAYS.items():
        for rel in files:
            add(module, rel)

    lines = [
        "//! Names of the Tauri commands invoked by the frontend, grouped like the",
        "//! former `src/lib/api/*.ts` modules. Generated by",
        "//! `scripts/gen-contract-commands.py`; a backend test checks every name",
        "//! is registered in `tauri::generate_handler!`.",
        "",
    ]
    all_names: set[str] = set()
    for module, names in groups.items():
        lines.append(f"pub mod {module} {{")
        for name in sorted(names):
            lines.append(f'    pub const {snake(name).upper()}: &str = "{name}";')
            all_names.add(name)
        lines.append("}\n")
    lines.append("/// Every command name the frontend invokes.")
    lines.append("pub const ALL: &[&str] = &[")
    lines.extend(f'    "{name}",' for name in sorted(all_names))
    lines.append("];")
    out = os.path.join(ROOT, "crates/cc-switch-contract/src/commands.rs")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"{len(groups)} modules, {len(all_names)} commands -> {os.path.relpath(out, ROOT)}")


if __name__ == "__main__":
    main()
