//! Emits a Rust module from the curated `index.ts` / `metadata.ts`, so the
//! Dioxus frontend embeds the same icon set as the React app.

use std::fs;
use std::io;
use std::path::Path;

use crate::index::{self, IndexFile};
use crate::svg;

/// One `iconMetadata` entry from `metadata.ts`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MetadataEntry {
    pub name: String,
    pub display_name: String,
    pub category: String,
    pub keywords: Vec<String>,
    pub default_color: Option<String>,
}

fn unquote(raw: &str) -> String {
    let t = raw.trim().trim_end_matches(',').trim();
    let t = t
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or(t);
    t.to_string()
}

/// Parses the `iconMetadata` object literal. Entries are two-space indented
/// `key: {` blocks with one `field: value,` per line, or a multi-line
/// `keywords: [` array, exactly as Prettier formats the file.
pub fn parse_metadata(src: &str) -> Vec<MetadataEntry> {
    let mut entries = Vec::new();
    let mut inside = false;
    let mut current: Option<MetadataEntry> = None;
    let mut in_keywords = false;
    for line in src.lines() {
        if !inside {
            if line.starts_with("export const iconMetadata") && line.ends_with("= {") {
                inside = true;
            }
            continue;
        }
        if line == "};" {
            break;
        }
        let trimmed = line.trim();
        if in_keywords {
            if trimmed.starts_with(']') {
                in_keywords = false;
            } else if let Some(entry) = current.as_mut() {
                entry.keywords.push(unquote(trimmed));
            }
            continue;
        }
        if let Some(rest) = line.strip_prefix("  ") {
            if !rest.starts_with(' ') && rest.ends_with(": {") {
                let key = rest.trim_end_matches(": {").trim().trim_matches('"');
                current = Some(MetadataEntry {
                    name: key.to_string(),
                    ..MetadataEntry::default()
                });
                continue;
            }
            if rest == "}," || rest == "}" {
                if let Some(entry) = current.take() {
                    entries.push(entry);
                }
                continue;
            }
        }
        let Some(entry) = current.as_mut() else {
            continue;
        };
        let Some((field, value)) = trimmed.split_once(':') else {
            continue;
        };
        match field.trim() {
            "name" => entry.name = unquote(value),
            "displayName" => entry.display_name = unquote(value),
            "category" => entry.category = unquote(value),
            "defaultColor" => entry.default_color = Some(unquote(value)),
            "keywords" => {
                let v = value.trim();
                if v.starts_with('[') && v.trim_end_matches(',').ends_with(']') {
                    let inner = v
                        .trim_end_matches(',')
                        .trim_start_matches('[')
                        .trim_end_matches(']');
                    entry.keywords = inner
                        .split(',')
                        .map(str::trim)
                        .filter(|s| !s.is_empty())
                        .map(unquote)
                        .collect();
                } else {
                    in_keywords = true;
                }
            }
            _ => {}
        }
    }
    entries
}

fn rust_str(s: &str) -> String {
    format!("{s:?}")
}

/// Renders the Rust source for `index` and `metadata`. `asset_prefix` is the
/// published directory of the URL icons (e.g. `/assets/icons`).
pub fn render_rust(index: &IndexFile, metadata: &[MetadataEntry], asset_prefix: &str) -> String {
    let mut out = String::from(
        "//! Generated by `icon-tools emit-rust` from src/icons/extracted; do not edit.\n\
         #![allow(clippy::all)]\n\n\
         use dioxus::prelude::*;\n\n\
         /// Icon metadata used for search and default colours.\n\
         pub struct IconMeta {\n    pub name: &'static str,\n    pub display_name: &'static str,\n    pub category: &'static str,\n    pub keywords: &'static [&'static str],\n    pub default_color: Option<&'static str>,\n}\n\n",
    );

    out.push_str(
        "/// Inline SVG icons, keyed by lowercase name.\npub static INLINE: &[(&str, &str)] = &[\n",
    );
    let mut inline: Vec<&index::InlineEntry> = index.inline.iter().collect();
    inline.sort_by(|a, b| a.key.cmp(&b.key));
    for entry in inline {
        let markup = svg::unescape_template_literal(&entry.body);
        out.push_str(&format!(
            "    ({}, {}),\n",
            rust_str(&entry.key),
            rust_str(&markup)
        ));
    }
    out.push_str("];\n\n");

    let mut urls: Vec<(&str, &str)> = index
        .urls
        .iter()
        .filter_map(|u| {
            index
                .imports
                .iter()
                .find(|i| i.ident == u.ident)
                .map(|i| (u.key.as_str(), i.file.as_str()))
        })
        .collect();
    urls.sort();
    out.push_str("/// Icons served as image URLs (raster files and oversized SVGs).\npub fn url_icon(name: &str) -> Option<Asset> {\n    match name {\n");
    for (key, file) in &urls {
        out.push_str(&format!(
            "        {} => Some(asset!({})),\n",
            rust_str(key),
            rust_str(&format!("{asset_prefix}/{file}"))
        ));
    }
    out.push_str("        _ => None,\n    }\n}\n\n");
    out.push_str("/// Names of the URL icons.\npub static URL_ICON_NAMES: &[&str] = &[\n");
    for (key, _) in &urls {
        out.push_str(&format!("    {},\n", rust_str(key)));
    }
    out.push_str("];\n\n");

    out.push_str("pub static METADATA: &[IconMeta] = &[\n");
    for m in metadata {
        let keywords: Vec<String> = m.keywords.iter().map(|k| rust_str(k)).collect();
        out.push_str(&format!(
            "    IconMeta {{ name: {}, display_name: {}, category: {}, keywords: &[{}], default_color: {} }},\n",
            rust_str(&m.name),
            rust_str(&m.display_name),
            rust_str(&m.category),
            keywords.join(", "),
            match &m.default_color {
                Some(c) => format!("Some({})", rust_str(c)),
                None => "None".to_string(),
            }
        ));
    }
    out.push_str("];\n");
    out
}

/// Files referenced by URL entries, to be copied next to the generated module.
pub fn url_files(index: &IndexFile) -> Vec<String> {
    index
        .urls
        .iter()
        .filter_map(|u| index.imports.iter().find(|i| i.ident == u.ident))
        .map(|i| i.file.clone())
        .collect()
}

/// Copies the URL icon files from `dir` into `assets_dir`.
pub fn copy_url_assets(dir: &Path, index: &IndexFile, assets_dir: &Path) -> io::Result<usize> {
    fs::create_dir_all(assets_dir)?;
    let mut copied = 0;
    for file in url_files(index) {
        fs::copy(dir.join(&file), assets_dir.join(&file))?;
        copied += 1;
    }
    Ok(copied)
}

#[cfg(test)]
mod tests {
    use super::*;

    const META: &str = r##"import { IconMetadata } from "@/types/icon";

export const iconMetadata: Record<string, IconMetadata> = {
  openai: {
    name: "openai",
    displayName: "OpenAI",
    category: "ai-provider",
    keywords: ["gpt", "chatgpt"],
    defaultColor: "#00A67E",
  },
  apikeyfun: {
    name: "apikeyfun",
    displayName: "APIKEY.FUN",
    category: "ai-provider",
    keywords: [
      "apikeyfun",
      "api key",
    ],
    defaultColor: "#9C3F00",
  },
  plain: {
    name: "plain",
    displayName: "Plain",
    category: "other",
    keywords: [],
  },
};
"##;

    #[test]
    fn parses_metadata_entries() {
        let entries = parse_metadata(META);
        assert_eq!(entries.len(), 3);
        assert_eq!(entries[0].display_name, "OpenAI");
        assert_eq!(entries[0].keywords, vec!["gpt", "chatgpt"]);
        assert_eq!(entries[0].default_color.as_deref(), Some("#00A67E"));
        assert_eq!(entries[1].keywords, vec!["apikeyfun", "api key"]);
        assert!(entries[2].keywords.is_empty());
        assert_eq!(entries[2].default_color, None);
    }

    #[test]
    fn renders_rust_module() {
        let index = index::parse_index(
            "import _logo from \"./logo.png\";\n\nexport const icons: Record<string, string> = {\n  b: `<svg>\\`x\\`</svg>`,\n  a: `<svg/>`,\n};\n\nexport const iconUrls: Record<string, string> = {\n  logo: _logo,\n};\n",
        )
        .unwrap();
        let out = render_rust(&index, &parse_metadata(META), "/assets/icons");
        assert!(out.contains("(\"a\", \"<svg/>\"),\n    (\"b\", \"<svg>`x`</svg>\"),"));
        assert!(out.contains("\"logo\" => Some(asset!(\"/assets/icons/logo.png\")),"));
        assert!(out.contains("IconMeta { name: \"openai\", display_name: \"OpenAI\""));
        assert_eq!(url_files(&index), vec!["logo.png"]);
    }
}
